export { default as Login } from './Login/Login';
export { default as NotFound } from './NotFound/NotFound';
export { default as Gallery } from './Private/Gallery/Gallery';
export { default as Home } from './Private/Home/Home';
export { default as Private } from './Private/Private';
export { default as Profile } from './Private/Profile/Profile';
export { default as Settings } from './Private/Settings/Settings';
export { default as Team } from './Private/Team/Team';
export { default as Web } from './Private/Web/Web';
export * from './Private/Web/components/Card';
export { default as Categories } from './Private/Web/Categories/Categories';
export { default as ConfigAside } from './Private/Web/components/ConfigAside/ConfigAside';
export { default as Principal } from './Private/Web/Principal/Principal';
export { default as Products } from './Private/Web/components/Products/Products';
export { default as Projects } from './Private/Web/components/Projects/Projects';
export { default as WebNav } from './Private/Web/components/WebNav/WebNav';
export * from './Private/Web/components';
