export { default as Login } from './Login/Login';
export { default as NotFound } from './NotFound/NotFound';
export { default as Gallery } from './Private/Gallery/Gallery';
export { default as Home } from './Private/Home/Home';
export { default as Private } from './Private/Private';
export { default as Profile } from './Private/Profile/Profile';
export { default as Settings } from './Private/Settings/Settings';
export { default as Team } from './Private/Team/Team';
export * from './Private/Web/Benefits';
export * from './Private/Web/Categories';
export { default as Principal } from './Private/Web/Principal/Principal';
export * from './Private/Web/Products';
export { default as Projects } from './Private/Web/Projects/Projects';
export { default as ConfigAside } from './Private/Web/components/ConfigAside/ConfigAside';
export * from './Private/Web/components';
export * from './Private/Web';
